#github.com/Elmatadorio/assignment 100935950

language: node_js
node_js:
  - 10.9.0

cache: npm

before install:
  - "npm congif set spin false"
  - npm i -g now

install:
  - npm install

script:
  - npm run build
  - npm run test

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true

